### ISSUE TITLE
[Bug] Create new repository image shows the wrong repository.

### ISSUE THREAD

**Issue by dusda** [skills/release-based-workflow#15] opened 2022-10-19 22:05 UTC
Under step 2 of _How to start this course_, the image of the new repository page is of a different repository.

**Comment by atraherajat** [comment] 2022-12-28 05:14
Duplicate of #2

**Comment by heiskr** [comment] 2023-02-16 05:29
Thanks for the issue. We've updated the courses to use a generic image.

**Closed by heiskr** 2023-02-16 05:29 UTC
Labels: bug
